# Profile initialization.

# Set up categories to specialties mapping.
CATEGORIES_SPECIALTIES_MAP =
	{
		'addiction therapist' => ['addiction'],
		'allergist' => [],
		'baby-proofing/home safety consultant' => [],
		'babysitter/mother\'s helper' => [],
		'bachelor\'s-level therapist' => [],
		'board-certified behavior analyst' => [],
		'child/clinical psychologist' => [],
		'child psychiatrist' => ['adoption'],
		'college admissions prep' => [],
		'college financial aid counselor' => [],
		'couples/family therapist' => [],
		'developmental-behavioral pediatrician' => ['behavior', 'developmental delay', 'toilet training', 'positive discipline'],
		'doula' => [],
		'eating disorders specialist' => [],
		'fertility specialist' => [],
		'genetics counselor' => [],
		'home allergens inspector' => [],
		'lactation/feeding consultant/counselor' => [],
		'learning disabilities specialist' => [],
		'master\'s-level therapist' => [],
		'midwife' => [],
		'music instructor' => [],
		'nutritionist' => [],
		'ob-gyn' => [],
		'occupational therapist' => [],
		'parenting coach/educator' => ['behavior', 'choosing a school (pre-K to 12)', 'positive discipline', 'parenting support', 'toilet training'],
		'pediatrician' => ['speech', 'trauma', 'weight management'],
		'pediatric dentist' => [],
		'physical therapist' => [],
		'reading/dyslexia specialist' => [],
		'school advocate' => [],
		'sleep expert' => [],
		'speech therapist' => [],
		'tutor' => []
	}
