development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr
    open_timeout: 6
    read_timeout: 6

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr
    open_timeout: 6
    read_timeout: 6

performance:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr
    open_timeout: 6
    read_timeout: 6

# Might need this for production.
production:
  solr:
    open_timeout: 6
    read_timeout: 6
#     path: /solr/default
